//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaycheckChallenge.CrossCutting.Globalization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaycheckChallenge.CrossCutting.Globalization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de admissão é obrigatória..
        /// </summary>
        public static string AdmissionDateIsMandatory {
            get {
                return ResourceManager.GetString("AdmissionDateIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O documento já está em uso..
        /// </summary>
        public static string DocumentIsAlreadyInUse {
            get {
                return ResourceManager.GetString("DocumentIsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O documento (CPF) precisa ter 11 dígitos..
        /// </summary>
        public static string DocumentIsMandatory {
            get {
                return ResourceManager.GetString("DocumentIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O primeiro nome deve ter entre 2 e 150 caracteres..
        /// </summary>
        public static string FirstNameHasInvalidLength {
            get {
                return ResourceManager.GetString("FirstNameHasInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O primeiro nome é obrigatório..
        /// </summary>
        public static string FirstNameIsMandatory {
            get {
                return ResourceManager.GetString("FirstNameIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O salário bruto é obrigatório..
        /// </summary>
        public static string GrossSalaryIsMandatory {
            get {
                return ResourceManager.GetString("GrossSalaryIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O documento (CPF) é inválido..
        /// </summary>
        public static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salário inválido..
        /// </summary>
        public static string InvalidSalary {
            get {
                return ResourceManager.GetString("InvalidSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O último nome deve ter entre 2 e 150 caracteres..
        /// </summary>
        public static string LastNameHasInvalidLength {
            get {
                return ResourceManager.GetString("LastNameHasInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O segundo nome é obrigatório..
        /// </summary>
        public static string LastNameIsMandatory {
            get {
                return ResourceManager.GetString("LastNameIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O setor deve ter entre 2 e 150 caracteres..
        /// </summary>
        public static string SectorHasInvalidLength {
            get {
                return ResourceManager.GetString("SectorHasInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O setor é obrigatório..
        /// </summary>
        public static string SectorIsMandatory {
            get {
                return ResourceManager.GetString("SectorIsMandatory", resourceCulture);
            }
        }
    }
}
